### PR TITLE
Open source batch release

### PR DESCRIPTION
**Pull request by dgonzalez**
Added: Pre-commit hook to include TF fmt, validation and linting
Fixed: Linting issues - no logic
Added: Split RDS user usage so we no longer need to use the master credentials
Added: Authorizer lambda now does not depend on Secrets Manager and is RBACed to avoid disclosure of secrets.
Added: Add explicit log groups
Removed: Monitoring stripped out from the infrastructure repository.
Fixed: Some refactoring for better readability

### CODE REVIEW

**Review by jasnell — APPROVED** [review]
LGTM but would be helpful if the significant changes in the batch could be summarized in the PR description (not blocking for landing but would be ideal to add)

**Comment by dgonzalez** [comment]
Doing it in 1 second.

**Comment by dgonzalez** [comment]
@jasnell can you have a look now?

**Review by colmharte — APPROVED** [review]

**Comment by jasnell** [comment]
Looks good @dgonzalez! thank you!

**Pull request merged**
